// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpkmrucokqzrprkjpysd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impwa21ydWNva3F6cnBya2pweXNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NjYzNzksImV4cCI6MjA2NDU0MjM3OX0.KiybnN_F9FiXKcINLDe_1H2_Ncx7e8D7R4X6y_c-SPQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);